<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBBxkrJx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBBxkrJx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBBxkrJx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBBxkrJx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBBxkrJx\App_KernelDevDebugContainer([
    'container.build_hash' => 'BBxkrJx',
    'container.build_id' => '6b3413a1',
    'container.build_time' => 1663234507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBBxkrJx');
