<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfRupmp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfRupmp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPfRupmp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPfRupmp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPfRupmp\App_KernelDevDebugContainer([
    'container.build_hash' => 'PfRupmp',
    'container.build_id' => 'd9d71d84',
    'container.build_time' => 1663329451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfRupmp');
