<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerONftixG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerONftixG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerONftixG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerONftixG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerONftixG\App_KernelDevDebugContainer([
    'container.build_hash' => 'ONftixG',
    'container.build_id' => '28d9d1cf',
    'container.build_time' => 1664474401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerONftixG');
